### ISSUE TITLE
problem converting strings with special characters

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/wp4-converters#17]
In the conversion process a number of files throw errors, such as: `Could not apply python string formatting to 'http://data.socialhistory.org/resource/hisco/occupationalTitle/bokhandelsdr{ng'
`
The special character also appears in the original .csv file, so it doesn't appear to be related to #15 . Other files have similar issues, specifically with the ` / `, which is used to separate multiple occupations.

**Comment by RinkeHoekstra** [comment]
Could you specify exactly which file throws the error?

**Comment by rlzijdeman** [comment]
sdh-public-datasets/se_CEDAR_HISCO.csv

**Comment by RinkeHoekstra** [comment]
@rlzijdemanit was actually a warning that was intentional. Sometimes URI's contain unmatched curly braces. This means that python string formatting (i.e. placing values for columns in the URI) does not work. Jinja2-style references to values do work in this case. 

In other words: it was not a bug, but just a cryptic warning message. Fixed in 16a24bc.

Could you give an example of a file that contains the `/` issue?

**Comment by rlzijdeman** [comment]
It broke on a very large file. Created a sample of that file with all nasty characters, including quotes and slashes, but it worked perfectly. Closing issue: issue not replicable.
